(()=>{'use strict';
const now=Math.max(2026,new Date().getFullYear()),MIN=-3200,MAX=now,MINSPAN=6,KEY='timelayers-ui-v3',D=typeof DATA!='undefined'?DATA:{people:[],works:[],events:[],periods:[]};
const n=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),num=(v,d=0)=>Number.isFinite(+v)?+v:d,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),title=x=>x.name||x.title||'Bez názvu',start=x=>num(x.start??x.year),end=x=>num(x.end??x.year??x.start,start(x)),imp=x=>clamp(num(x.importance,3),1,5),cats=x=>(x.categories||[]).map(n),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fy=y=>Math.round(y)<0?`${Math.abs(Math.round(y)).toLocaleString('cs-CZ')} př. n. l.`:Math.round(y).toLocaleString('cs-CZ'),fr=x=>(x.living||end(x)>=MAX)&&x.kind==='person'?`${fy(start(x))}–dnes`:Math.round(start(x))===Math.round(end(x))?fy(start(x)):`${fy(start(x))}–${fy(end(x))}`;
const P=(D.people||[]).map(x=>({...x,kind:'person'})),W=(D.works||[]).map(x=>({...x,kind:'work',start:num(x.year,x.start),end:num(x.year,x.start)})),E=(D.events||[]).map(x=>({...x,kind:'event'})),R=(D.periods||[]).map(x=>({...x,kind:'period'})),byPerson=new Map(P.map(x=>[x.id,x]));
const ruler=x=>x.scope==='ruler'||cats(x).includes('ruler'),monument=x=>cats(x).some(c=>['monument','castle','stavba'].includes(c))||/(hrad|zámek|katedrál|pyramid|kolose|stonehenge|chrám|most|věž|palác)/i.test(title(x)),tech=x=>x.scope==='tech'||cats(x).some(c=>['science','invention','vynález'].includes(c)),czech=x=>x.scope==='czech'||cats(x).includes('czech-history'),war=x=>cats(x).includes('war')||/(válk|bitv|invaz|okupac|atentát|povstání)/i.test(title(x));
const L=[
['authors','Autoři','♙','#7357e8',()=>P],['works','Literární díla','▤','#a14ee2',()=>W],['rulers','Vládci a prezidenti','♛','#be842b',()=>E.filter(ruler)],['czech','České dějiny','⌂','#1685d1',()=>E.filter(x=>!ruler(x)&&!monument(x)&&!tech(x)&&czech(x))],['world','Svět a války','◎','#d9565d',()=>E.filter(x=>!ruler(x)&&!monument(x)&&!tech(x)&&!czech(x))],['tech','Věda a vynálezy','✦','#e29622',()=>E.filter(x=>!ruler(x)&&!monument(x)&&tech(x))],['monuments','Stavby a hrady','♜','#85633d',()=>E.filter(x=>!ruler(x)&&monument(x))],['periods','Historická období','≡','#2f9674',()=>R]
].map(([id,label,icon,color,get])=>({id,label,icon,color,get}));
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{};
const S={a:clamp(num(saved.a,1780),MIN,MAX-MINSPAN),b:clamp(num(saved.b,MAX),MIN+MINSPAN,MAX),on:new Set(saved.on||['authors','works','rulers','czech','world','periods']),theme:saved.theme==='dark'?'dark':'light',level:saved.level||'balanced',q:'',selected:null,drag:null};if(S.b-S.a<MINSPAN)S.b=S.a+MINSPAN;
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify({a:S.a,b:S.b,on:[...S.on],theme:S.theme,level:S.level}))}catch{}};
document.documentElement.dataset.modernTheme=S.theme;document.title='Časovrstvy — souvislosti v čase';
document.body.innerHTML=`<div class="cv"><header><button class="brand" data-act="layers"><b>◫</b><span><strong>Časovrstvy</strong><small>souvislosti v čase</small></span></button><div class="range"><small>AKTUÁLNÍ VÝŘEZ</small><b id="range"></b></div><label class="search"><i>⌕</i><input id="search" placeholder="Hledat autora, dílo nebo událost…"><kbd>⌘ K</kbd></label><div id="results" class="results" hidden></div><select id="level"><option value="basic">Základy</option><option value="balanced">Vyváženě</option><option value="detailed">Podrobně</option></select><button class="round" data-act="theme">${S.theme==='dark'?'☀':'☾'}</button><button class="round" data-act="full">⛶</button></header>
<nav class="rail"><button data-act="layers">◫<span>Vrstvy</span></button><button data-act="zin">＋<span>Přiblížit</span></button><button data-act="zout">−<span>Oddálit</span></button><button data-act="fit">⌗<span>Celá osa</span></button></nav>
<aside class="layers" id="layers"><div class="lh"><div><small>OBSAH</small><h2>Vrstvy časové osy</h2></div><button data-act="closeLayers">×</button></div><div class="presets"><button data-set="all">Vše</button><button data-set="history">Historie</button><button data-set="literature">Literatura</button><button data-set="context">Literatura + kontext</button></div><div id="layerList"></div><hr><small class="ey">RYCHLÝ PŘESUN</small><div class="eras"><button data-era="ancient">Starověk</button><button data-era="medieval">Středověk</button><button data-era="renaissance">Renesance</button><button data-era="19">19. století</button><button data-era="20">20. století</button><button data-era="now">Současnost</button></div><hr><small class="ey">VLASTNÍ ROZSAH</small><div class="custom"><input id="from" type="number"><span>—</span><input id="to" type="number"><button data-act="apply">Použít</button></div></aside><button class="scrim" data-act="closeLayers"></button>
<main><section class="timeline" id="timeline"><div class="ruler" id="ruler"></div><div class="focus"><span id="focus"></span></div><div class="tracks" id="tracks"></div></section><footer><div><small>CELÁ HISTORIE</small><b>${fy(MIN)} — ${fy(MAX)}</b></div><div class="map" id="map"><div id="density"></div><i id="window"></i></div><div class="zoom"><button data-act="zout">−</button><input id="zoom" type="range" min="0" max="100"><button data-act="zin">＋</button></div></footer></main>
<aside class="detail" id="detail"><div class="hero"><button data-act="closeDetail">×</button><small id="dtype"></small></div><div class="dbody"><time id="ddate"></time><h1 id="dtitle"></h1><p id="dtext"></p><div id="dmeta"></div><div id="related"></div><a id="source" target="_blank" rel="noopener">Otevřít ověřený zdroj ↗</a></div></aside><button class="dscrim" data-act="closeDetail"></button></div>`;
const $=s=>document.querySelector(s),app=$('.cv'),timeline=$('#timeline'),tracks=$('#tracks'),rulerEl=$('#ruler'),layers=$('#layers'),results=$('#results'),search=$('#search'),detail=$('#detail'),level=$('#level');level.value=S.level;
const kind=x=>x.kind==='person'?'Autor':x.kind==='work'?'Literární dílo':x.kind==='period'?'Historické období':ruler(x)?'Vládce nebo prezident':tech(x)?'Věda a vynález':monument(x)?'Stavba nebo památka':czech(x)?'České dějiny':war(x)?'Válka a světové dějiny':'Světové dějiny';
const desc=x=>x.summary||(x.kind==='person'?(W.filter(w=>w.authorId===x.id).length?`Autor spojený s díly ${W.filter(w=>w.authorId===x.id).slice(0,4).map(title).join(', ')}.`:'Významná osobnost literárních dějin.'):x.kind==='work'&&byPerson.get(x.authorId)?`Literární dílo autora ${byPerson.get(x.authorId).name}.`:'Významná položka společné historické a kulturní časové osy.');
const persistRange=(a,b)=>{let span=clamp(b-a,MINSPAN,MAX-MIN),c=(a+b)/2;a=c-span/2;b=c+span/2;if(a<MIN){b+=MIN-a;a=MIN}if(b>MAX){a-=b-MAX;b=MAX}S.a=a;S.b=b;save();render()};
const zoom=(f,r=.5)=>{let span=S.b-S.a,next=clamp(span*f,MINSPAN,MAX-MIN),anchor=S.a+span*r;persistRange(anchor-next*r,anchor+next*(1-r))};
const xfor=(y,w)=>(y-S.a)/(S.b-S.a)*w,step=span=>[1,2,5,10,20,25,50,100,200,250,500,1000,2000].find(v=>span/v<=12)||5000;
const controls=()=>{$('#layerList').innerHTML=L.map(l=>`<button class="layer ${S.on.has(l.id)?'on':''}" data-layer="${l.id}" style="--c:${l.color}"><i>${l.icon}</i><span><b>${l.label}</b><small>${l.get().length.toLocaleString('cs-CZ')} položek</small></span><em></em></button>`).join('')};
const filtered=(l,w)=>{let q=n(S.q),items=l.get().filter(x=>end(x)>=S.a&&start(x)<=S.b);if(q)items=items.filter(x=>n(`${title(x)} ${desc(x)} ${(x.keywords||[]).join(' ')}`).includes(q));let span=S.b-S.a,t=S.level==='basic'?4:S.level==='balanced'?3:1;if(span>1200)items=items.filter(x=>imp(x)>=Math.max(4,t));else if(span>450)items=items.filter(x=>imp(x)>=t);let limit=Math.max(18,Math.floor(w/35)*(S.level==='detailed'?4:S.level==='balanced'?2.5:1.5));return items.sort((a,b)=>start(a)-start(b)||imp(b)-imp(a)||title(a).localeCompare(title(b),'cs')).slice(0,limit)};
const hash=s=>{let h=0;for(let c of String(s))h=(Math.imul(h,31)+c.charCodeAt(0))|0;return Math.abs(h)};
const track=(l,w)=>{let items=filtered(l,w),h=items.length>55?174:items.length>25?146:120,lanes=h>160?4:h>135?3:2,span=S.b-S.a,compact=span>400,html=items.map(o=>{let a=clamp(start(o),S.a,S.b),b=clamp(end(o),S.a,S.b),sx=xfor(a,w),ex=xfor(b,w),cx=xfor((a+b)/2,w),lane=hash(`${l.id}${o.id||title(o)}`)%lanes,top=45+lane*((h-54)/lanes),dur=Math.max(0,b-a),dw=Math.max(3,ex-sx),duration=dur>span*.0018||o.kind==='person'&&end(o)>start(o),show=!compact||imp(o)>=5||dw>90,cls=`item ${duration?'duration':'point'} ${show?'labelled':'compact'} ${war(o)?'war':''} ${S.selected?.id===o.id&&S.selected?.kind===o.kind?'selected':''}`;return duration?`<button class="${cls}" data-kind="${o.kind}" data-id="${esc(o.id)}" style="--c:${l.color};left:${Math.max(0,sx)}px;top:${top}px;width:${dw}px"><i class="bar"></i>${show?`<span class="tag" style="left:${clamp(dw/2,12,Math.max(12,dw-12))}px"><b>${esc(title(o))}</b><small>${esc(fr(o))}</small></span>`:''}</button>`:`<button class="${cls}" data-kind="${o.kind}" data-id="${esc(o.id)}" style="--c:${l.color};left:${cx}px;top:${top}px"><i class="dot"></i>${show?`<span class="tag"><b>${esc(title(o))}</b><small>${esc(fr(o))}</small></span>`:''}</button>`}).join('');return `<section class="track" style="--c:${l.color};height:${h}px"><div class="tname"><i>${l.icon}</i><span><b>${l.label}</b><small>${items.length} ve výřezu</small></span></div><div class="canvas"><i class="axis"></i>${html}</div></section>`};
const render=()=>{let w=Math.max(650,tracks.clientWidth||timeline.clientWidth||1200),span=S.b-S.a,st=step(span),first=Math.ceil(S.a/st)*st,ticks=[];for(let y=first;y<=S.b+st*.05;y+=st)ticks.push(`<i style="left:${xfor(y,w)}px"><span>${fy(y)}</span></i>`);rulerEl.innerHTML=ticks.join('');$('#range').textContent=`${fy(S.a)} — ${fy(S.b)}`;$('#focus').textContent=fy((S.a+S.b)/2);$('#from').value=Math.round(S.a);$('#to').value=Math.round(S.b);tracks.innerHTML=L.filter(l=>S.on.has(l.id)).map(l=>track(l,w)).join('');let full=MAX-MIN;$('#window').style.left=`${(S.a-MIN)/full*100}%`;$('#window').style.width=`${Math.max(.8,(S.b-S.a)/full*100)}%`;$('#zoom').value=String(clamp(100*Math.log(full/(S.b-S.a))/Math.log(full/MINSPAN),0,100));controls()};
const all=[...P,...W,...E,...R],find=(k,id)=>(k==='person'?P:k==='work'?W:k==='period'?R:E).find(x=>String(x.id)===String(id));
const related=x=>x.kind==='person'?W.filter(w=>w.authorId===x.id).slice(0,7):x.kind==='work'&&byPerson.get(x.authorId)?[byPerson.get(x.authorId),...E.filter(e=>start(e)<=start(x)&&end(e)>=start(x)).slice(0,4)]:all.filter(o=>o.id!==x.id&&Math.abs((start(o)+end(o)-start(x)-end(x))/2)<=Math.max(5,(S.b-S.a)*.025)).slice(0,6);
const open=x=>{if(!x)return;S.selected=x;$('#dtype').textContent=kind(x);$('#ddate').textContent=fr(x);$('#dtitle').textContent=title(x);$('#dtext').textContent=desc(x);let m=[];if(x.kind==='work'&&byPerson.get(x.authorId))m.push(['Autor',byPerson.get(x.authorId).name]);if(x.region)m.push(['Území',x.region]);if(x.role)m.push(['Role',x.role]);if(x.keywords?.length)m.push(['Klíčová slova',x.keywords.slice(0,6).join(' · ')]);$('#dmeta').innerHTML=m.length?`<dl>${m.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl>`:'';let rel=related(x);$('#related').innerHTML=rel.length?`<h3>SOUVISEJÍCÍ POLOŽKY</h3>${rel.map(o=>`<button data-rel="${o.kind}" data-rid="${esc(o.id)}"><small>${kind(o)}</small><b>${esc(title(o))}</b></button>`).join('')}`:'';$('#source').href=x.wiki||`https://cs.wikipedia.org/wiki/Special:Search?search=${encodeURIComponent(title(x))}`;detail.classList.add('open');$('.dscrim').classList.add('open');render()};
const close=()=>{S.selected=null;detail.classList.remove('open');$('.dscrim').classList.remove('open');render()};
const goto=x=>{let c=(start(x)+end(x))/2,s=clamp(Math.max(18,(end(x)-start(x))*3.5),MINSPAN,420);S.q='';search.value='';results.hidden=true;S.a=c-s/2;S.b=c+s/2;open(x)};
const searchNow=()=>{let q=n(search.value.trim());S.q=q;if(!q){results.hidden=true;render();return}let a=all.filter(x=>n(`${title(x)} ${desc(x)} ${(x.keywords||[]).join(' ')}`).includes(q)).sort((a,b)=>imp(b)-imp(a)||start(a)-start(b)).slice(0,9);results.innerHTML=a.length?a.map(x=>`<button data-sk="${x.kind}" data-sid="${esc(x.id)}"><small>${kind(x)} · ${fr(x)}</small><b>${esc(title(x))}</b><i>›</i></button>`).join(''):'<p>Žádná odpovídající položka.</p>';results.hidden=false;render()};
const setLayers=p=>{let sets={all:L.map(x=>x.id),history:['rulers','czech','world','tech','monuments','periods'],literature:['authors','works'],context:['authors','works','rulers','czech','world','periods']};S.on=new Set(sets[p]||[]);save();render()};
const era={ancient:[-800,500],medieval:[500,1500],renaissance:[1350,1650],'19':[1800,1900],'20':[1900,2000],now:[1945,MAX]};
app.addEventListener('click',e=>{let a=e.target.closest('[data-act]');if(a){let v=a.dataset.act;if(v==='layers')layers.classList.add('open'),$('.scrim').classList.add('open');if(v==='closeLayers')layers.classList.remove('open'),$('.scrim').classList.remove('open');if(v==='zin')zoom(.68);if(v==='zout')zoom(1.47);if(v==='fit')persistRange(MIN,MAX);if(v==='theme'){S.theme=S.theme==='dark'?'light':'dark';document.documentElement.dataset.modernTheme=S.theme;a.textContent=S.theme==='dark'?'☀':'☾';save()}if(v==='full')document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();if(v==='closeDetail')close();if(v==='apply'){let f=num($('#from').value,S.a),t=num($('#to').value,S.b);if(t>f){persistRange(f,t);layers.classList.remove('open');$('.scrim').classList.remove('open')}}return}let l=e.target.closest('[data-layer]');if(l){S.on.has(l.dataset.layer)?S.on.delete(l.dataset.layer):S.on.add(l.dataset.layer);save();render();return}let set=e.target.closest('[data-set]');if(set){setLayers(set.dataset.set);return}let er=e.target.closest('[data-era]');if(er){persistRange(...era[er.dataset.era]);layers.classList.remove('open');$('.scrim').classList.remove('open');return}let it=e.target.closest('.item');if(it){open(find(it.dataset.kind,it.dataset.id));return}let sr=e.target.closest('[data-sk]');if(sr){goto(find(sr.dataset.sk,sr.dataset.sid));return}let rr=e.target.closest('[data-rel]');if(rr)goto(find(rr.dataset.rel,rr.dataset.rid))});
search.addEventListener('input',searchNow);level.addEventListener('change',()=>{S.level=level.value;save();render()});$('#zoom').addEventListener('input',()=>{let full=MAX-MIN,s=full*Math.pow(MINSPAN/full,+$('#zoom').value/100),c=(S.a+S.b)/2;persistRange(c-s/2,c+s/2)});
timeline.addEventListener('wheel',e=>{if(e.target.closest('button,input,select,a'))return;e.preventDefault();let r=timeline.getBoundingClientRect(),ratio=clamp((e.clientX-r.left)/r.width,0,1);if(e.shiftKey||Math.abs(e.deltaX)>Math.abs(e.deltaY)*.7){let d=(e.deltaX+(e.shiftKey?e.deltaY:0))/r.width*(S.b-S.a);persistRange(S.a+d,S.b+d)}else zoom(Math.exp(e.deltaY*.00115),ratio)},{passive:false});
timeline.addEventListener('pointerdown',e=>{if(e.button||e.target.closest('button,input,a'))return;S.drag={x:e.clientX,a:S.a,b:S.b,id:e.pointerId};timeline.setPointerCapture(e.pointerId);timeline.classList.add('dragging')});timeline.addEventListener('pointermove',e=>{if(!S.drag)return;let y=-(e.clientX-S.drag.x)/timeline.clientWidth*(S.drag.b-S.drag.a),a=S.drag.a+y,b=S.drag.b+y,s=b-a;if(a<MIN){a=MIN;b=a+s}if(b>MAX){b=MAX;a=b-s}S.a=a;S.b=b;requestAnimationFrame(render)});const undrag=e=>{if(!S.drag)return;try{timeline.releasePointerCapture(S.drag.id)}catch{}S.drag=null;timeline.classList.remove('dragging');save()};timeline.addEventListener('pointerup',undrag);timeline.addEventListener('pointercancel',undrag);timeline.addEventListener('dblclick',e=>{if(!e.target.closest('button')){let r=timeline.getBoundingClientRect();zoom(.5,clamp((e.clientX-r.left)/r.width,0,1))}});
$('#map').addEventListener('pointerdown',e=>{let r=$('#map').getBoundingClientRect(),y=MIN+clamp((e.clientX-r.left)/r.width,0,1)*(MAX-MIN),s=S.b-S.a;persistRange(y-s/2,y+s/2)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus()}if(e.key==='Escape'){if(detail.classList.contains('open'))close();else{layers.classList.remove('open');$('.scrim').classList.remove('open');results.hidden=true}}});window.addEventListener('resize',render);
let buckets=Array(100).fill(0);all.forEach(x=>buckets[clamp(Math.floor(((start(x)+end(x))/2-MIN)/(MAX-MIN)*100),0,99)]+=imp(x));let mx=Math.max(...buckets,1);$('#density').innerHTML=buckets.map((v,i)=>`<i style="left:${i}%;height:${Math.max(4,v/mx*100)}%"></i>`).join('');controls();render();
})();